version: '3'

services:
  db:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: "kothinPassword"
      MYSQL_DATABASE: "order"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "kothinPassword"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080"

volumes:
  db-data:
